//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TicketClientApp.TicketWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AD_AuthenticateWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AD_AuthenticateWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback logOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTicketRankingResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoPickupTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchNewConversations_OperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchNewConversationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Report_ticketSummeryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllProjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback ticketRandomChartOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAdUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AD_AuthenticateWebService() {
            this.Url = global::TicketClientApp.Properties.Settings.Default.WindowsFormsApp1_TicketWebService_AD_AuthenticateWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authenticateCompletedEventHandler authenticateCompleted;
        
        /// <remarks/>
        public event logOutCompletedEventHandler logOutCompleted;
        
        /// <remarks/>
        public event GetTicketRankingResultCompletedEventHandler GetTicketRankingResultCompleted;
        
        /// <remarks/>
        public event AutoPickupTicketCompletedEventHandler AutoPickupTicketCompleted;
        
        /// <remarks/>
        public event FetchNewConversations_CompletedEventHandler FetchNewConversations_Completed;
        
        /// <remarks/>
        public event FetchNewConversationsCompletedEventHandler FetchNewConversationsCompleted;
        
        /// <remarks/>
        public event UserAuthenticateCompletedEventHandler UserAuthenticateCompleted;
        
        /// <remarks/>
        public event Report_ticketSummeryCompletedEventHandler Report_ticketSummeryCompleted;
        
        /// <remarks/>
        public event GetAllProjectsCompletedEventHandler GetAllProjectsCompleted;
        
        /// <remarks/>
        public event GetProjectCompletedEventHandler GetProjectCompleted;
        
        /// <remarks/>
        public event ticketRandomChartCompletedEventHandler ticketRandomChartCompleted;
        
        /// <remarks/>
        public event findAdUsersCompletedEventHandler findAdUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/authenticate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticateRetVal authenticate(string username, string password) {
            object[] results = this.Invoke("authenticate", new object[] {
                        username,
                        password});
            return ((AuthenticateRetVal)(results[0]));
        }
        
        /// <remarks/>
        public void authenticateAsync(string username, string password) {
            this.authenticateAsync(username, password, null);
        }
        
        /// <remarks/>
        public void authenticateAsync(string username, string password, object userState) {
            if ((this.authenticateOperationCompleted == null)) {
                this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
            }
            this.InvokeAsync("authenticate", new object[] {
                        username,
                        password}, this.authenticateOperationCompleted, userState);
        }
        
        private void OnauthenticateOperationCompleted(object arg) {
            if ((this.authenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/logOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string logOut(string token) {
            object[] results = this.Invoke("logOut", new object[] {
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void logOutAsync(string token) {
            this.logOutAsync(token, null);
        }
        
        /// <remarks/>
        public void logOutAsync(string token, object userState) {
            if ((this.logOutOperationCompleted == null)) {
                this.logOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogOutOperationCompleted);
            }
            this.InvokeAsync("logOut", new object[] {
                        token}, this.logOutOperationCompleted, userState);
        }
        
        private void OnlogOutOperationCompleted(object arg) {
            if ((this.logOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logOutCompleted(this, new logOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTicketRankingResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RankingTicketResult_forSan GetTicketRankingResult(string san_list, System.DateTime dt_start, System.DateTime dt_end) {
            object[] results = this.Invoke("GetTicketRankingResult", new object[] {
                        san_list,
                        dt_start,
                        dt_end});
            return ((RankingTicketResult_forSan)(results[0]));
        }
        
        /// <remarks/>
        public void GetTicketRankingResultAsync(string san_list, System.DateTime dt_start, System.DateTime dt_end) {
            this.GetTicketRankingResultAsync(san_list, dt_start, dt_end, null);
        }
        
        /// <remarks/>
        public void GetTicketRankingResultAsync(string san_list, System.DateTime dt_start, System.DateTime dt_end, object userState) {
            if ((this.GetTicketRankingResultOperationCompleted == null)) {
                this.GetTicketRankingResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTicketRankingResultOperationCompleted);
            }
            this.InvokeAsync("GetTicketRankingResult", new object[] {
                        san_list,
                        dt_start,
                        dt_end}, this.GetTicketRankingResultOperationCompleted, userState);
        }
        
        private void OnGetTicketRankingResultOperationCompleted(object arg) {
            if ((this.GetTicketRankingResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTicketRankingResultCompleted(this, new GetTicketRankingResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutoPickupTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ticketPool AutoPickupTicket(string token) {
            object[] results = this.Invoke("AutoPickupTicket", new object[] {
                        token});
            return ((ticketPool)(results[0]));
        }
        
        /// <remarks/>
        public void AutoPickupTicketAsync(string token) {
            this.AutoPickupTicketAsync(token, null);
        }
        
        /// <remarks/>
        public void AutoPickupTicketAsync(string token, object userState) {
            if ((this.AutoPickupTicketOperationCompleted == null)) {
                this.AutoPickupTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoPickupTicketOperationCompleted);
            }
            this.InvokeAsync("AutoPickupTicket", new object[] {
                        token}, this.AutoPickupTicketOperationCompleted, userState);
        }
        
        private void OnAutoPickupTicketOperationCompleted(object arg) {
            if ((this.AutoPickupTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoPickupTicketCompleted(this, new AutoPickupTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchNewConversations_", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NewConversations FetchNewConversations_(string token) {
            object[] results = this.Invoke("FetchNewConversations_", new object[] {
                        token});
            return ((NewConversations)(results[0]));
        }
        
        /// <remarks/>
        public void FetchNewConversations_Async(string token) {
            this.FetchNewConversations_Async(token, null);
        }
        
        /// <remarks/>
        public void FetchNewConversations_Async(string token, object userState) {
            if ((this.FetchNewConversations_OperationCompleted == null)) {
                this.FetchNewConversations_OperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchNewConversations_OperationCompleted);
            }
            this.InvokeAsync("FetchNewConversations_", new object[] {
                        token}, this.FetchNewConversations_OperationCompleted, userState);
        }
        
        private void OnFetchNewConversations_OperationCompleted(object arg) {
            if ((this.FetchNewConversations_Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchNewConversations_Completed(this, new FetchNewConversations_CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchNewConversations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NewConversations FetchNewConversations(string token) {
            object[] results = this.Invoke("FetchNewConversations", new object[] {
                        token});
            return ((NewConversations)(results[0]));
        }
        
        /// <remarks/>
        public void FetchNewConversationsAsync(string token) {
            this.FetchNewConversationsAsync(token, null);
        }
        
        /// <remarks/>
        public void FetchNewConversationsAsync(string token, object userState) {
            if ((this.FetchNewConversationsOperationCompleted == null)) {
                this.FetchNewConversationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchNewConversationsOperationCompleted);
            }
            this.InvokeAsync("FetchNewConversations", new object[] {
                        token}, this.FetchNewConversationsOperationCompleted, userState);
        }
        
        private void OnFetchNewConversationsOperationCompleted(object arg) {
            if ((this.FetchNewConversationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchNewConversationsCompleted(this, new FetchNewConversationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserAuthenticate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAuthenticateRet UserAuthenticate(string username, string password) {
            object[] results = this.Invoke("UserAuthenticate", new object[] {
                        username,
                        password});
            return ((UserAuthenticateRet)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthenticateAsync(string username, string password) {
            this.UserAuthenticateAsync(username, password, null);
        }
        
        /// <remarks/>
        public void UserAuthenticateAsync(string username, string password, object userState) {
            if ((this.UserAuthenticateOperationCompleted == null)) {
                this.UserAuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthenticateOperationCompleted);
            }
            this.InvokeAsync("UserAuthenticate", new object[] {
                        username,
                        password}, this.UserAuthenticateOperationCompleted, userState);
        }
        
        private void OnUserAuthenticateOperationCompleted(object arg) {
            if ((this.UserAuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthenticateCompleted(this, new UserAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Report_ticketSummery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public reportResult Report_ticketSummery(int tso_id, string serviceLine) {
            object[] results = this.Invoke("Report_ticketSummery", new object[] {
                        tso_id,
                        serviceLine});
            return ((reportResult)(results[0]));
        }
        
        /// <remarks/>
        public void Report_ticketSummeryAsync(int tso_id, string serviceLine) {
            this.Report_ticketSummeryAsync(tso_id, serviceLine, null);
        }
        
        /// <remarks/>
        public void Report_ticketSummeryAsync(int tso_id, string serviceLine, object userState) {
            if ((this.Report_ticketSummeryOperationCompleted == null)) {
                this.Report_ticketSummeryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReport_ticketSummeryOperationCompleted);
            }
            this.InvokeAsync("Report_ticketSummery", new object[] {
                        tso_id,
                        serviceLine}, this.Report_ticketSummeryOperationCompleted, userState);
        }
        
        private void OnReport_ticketSummeryOperationCompleted(object arg) {
            if ((this.Report_ticketSummeryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Report_ticketSummeryCompleted(this, new Report_ticketSummeryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllProjects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public fava_project_summery GetAllProjects(int main_workingCategory_id, string projectsMode) {
            object[] results = this.Invoke("GetAllProjects", new object[] {
                        main_workingCategory_id,
                        projectsMode});
            return ((fava_project_summery)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllProjectsAsync(int main_workingCategory_id, string projectsMode) {
            this.GetAllProjectsAsync(main_workingCategory_id, projectsMode, null);
        }
        
        /// <remarks/>
        public void GetAllProjectsAsync(int main_workingCategory_id, string projectsMode, object userState) {
            if ((this.GetAllProjectsOperationCompleted == null)) {
                this.GetAllProjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllProjectsOperationCompleted);
            }
            this.InvokeAsync("GetAllProjects", new object[] {
                        main_workingCategory_id,
                        projectsMode}, this.GetAllProjectsOperationCompleted, userState);
        }
        
        private void OnGetAllProjectsOperationCompleted(object arg) {
            if ((this.GetAllProjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllProjectsCompleted(this, new GetAllProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public fava_project_summery GetProject(string project_id) {
            object[] results = this.Invoke("GetProject", new object[] {
                        project_id});
            return ((fava_project_summery)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectAsync(string project_id) {
            this.GetProjectAsync(project_id, null);
        }
        
        /// <remarks/>
        public void GetProjectAsync(string project_id, object userState) {
            if ((this.GetProjectOperationCompleted == null)) {
                this.GetProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectOperationCompleted);
            }
            this.InvokeAsync("GetProject", new object[] {
                        project_id}, this.GetProjectOperationCompleted, userState);
        }
        
        private void OnGetProjectOperationCompleted(object arg) {
            if ((this.GetProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectCompleted(this, new GetProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ticketRandomChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ticketRandomChart(int rootCategoryId, int chartId) {
            object[] results = this.Invoke("ticketRandomChart", new object[] {
                        rootCategoryId,
                        chartId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ticketRandomChartAsync(int rootCategoryId, int chartId) {
            this.ticketRandomChartAsync(rootCategoryId, chartId, null);
        }
        
        /// <remarks/>
        public void ticketRandomChartAsync(int rootCategoryId, int chartId, object userState) {
            if ((this.ticketRandomChartOperationCompleted == null)) {
                this.ticketRandomChartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnticketRandomChartOperationCompleted);
            }
            this.InvokeAsync("ticketRandomChart", new object[] {
                        rootCategoryId,
                        chartId}, this.ticketRandomChartOperationCompleted, userState);
        }
        
        private void OnticketRandomChartOperationCompleted(object arg) {
            if ((this.ticketRandomChartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ticketRandomChartCompleted(this, new ticketRandomChartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/findAdUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public adUser[] findAdUsers(string searchInput) {
            object[] results = this.Invoke("findAdUsers", new object[] {
                        searchInput});
            return ((adUser[])(results[0]));
        }
        
        /// <remarks/>
        public void findAdUsersAsync(string searchInput) {
            this.findAdUsersAsync(searchInput, null);
        }
        
        /// <remarks/>
        public void findAdUsersAsync(string searchInput, object userState) {
            if ((this.findAdUsersOperationCompleted == null)) {
                this.findAdUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAdUsersOperationCompleted);
            }
            this.InvokeAsync("findAdUsers", new object[] {
                        searchInput}, this.findAdUsersOperationCompleted, userState);
        }
        
        private void OnfindAdUsersOperationCompleted(object arg) {
            if ((this.findAdUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAdUsersCompleted(this, new findAdUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRetVal {
        
        private string typeField;
        
        private string messageField;
        
        private object tokenField;
        
        private string sanField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public object token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string san {
            get {
                return this.sanField;
            }
            set {
                this.sanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class adUser {
        
        private string cnField;
        
        private string mobileField;
        
        private string emailField;
        
        private string samField;
        
        /// <remarks/>
        public string cn {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
            }
        }
        
        /// <remarks/>
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string sam {
            get {
                return this.samField;
            }
            set {
                this.samField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class involved_user {
        
        private string sanField;
        
        private string cnField;
        
        private string profileImgField;
        
        private int estimatedHourField;
        
        /// <remarks/>
        public string san {
            get {
                return this.sanField;
            }
            set {
                this.sanField = value;
            }
        }
        
        /// <remarks/>
        public string cn {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
            }
        }
        
        /// <remarks/>
        public string profileImg {
            get {
                return this.profileImgField;
            }
            set {
                this.profileImgField = value;
            }
        }
        
        /// <remarks/>
        public int estimatedHour {
            get {
                return this.estimatedHourField;
            }
            set {
                this.estimatedHourField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class project_ticket {
        
        private int cntField;
        
        private string textField;
        
        private string rowsField;
        
        /// <remarks/>
        public int cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class project_info {
        
        private int ticket_countField;
        
        private int ticket_open_countField;
        
        private int ticket_close_countField;
        
        private int execute_dayField;
        
        private string strDate_infoField;
        
        private string execute_infoField;
        
        private string titleField;
        
        private int prj_idField;
        
        private int cat_idField;
        
        private string cat_titleField;
        
        private string director_sanField;
        
        private string directorField;
        
        private string director_imgField;
        
        private int work_daysField;
        
        private int vacation_daysField;
        
        private int est_working_hourField;
        
        private bool approval_resultField;
        
        private string approval_detailsField;
        
        private string finish_userSanField;
        
        private int proggress_percentField;
        
        private string strCurrentProggressPecrcentField;
        
        private string descField;
        
        private string creted_sanField;
        
        private string creatorField;
        
        private System.Nullable<System.DateTime> est_startField;
        
        private System.Nullable<System.DateTime> est_endField;
        
        private System.Nullable<System.DateTime> createdField;
        
        private System.Nullable<System.DateTime> finish_dateField;
        
        private System.Nullable<System.DateTime> lastTicket_finishDateField;
        
        private System.Nullable<System.DateTime> lastMajor_updateDateField;
        
        private int yearField;
        
        private System.Nullable<System.DateTime> merging_dateField;
        
        private int merged_toField;
        
        private string merging_infoField;
        
        private string merged_project_search_tagField;
        
        /// <remarks/>
        public int ticket_count {
            get {
                return this.ticket_countField;
            }
            set {
                this.ticket_countField = value;
            }
        }
        
        /// <remarks/>
        public int ticket_open_count {
            get {
                return this.ticket_open_countField;
            }
            set {
                this.ticket_open_countField = value;
            }
        }
        
        /// <remarks/>
        public int ticket_close_count {
            get {
                return this.ticket_close_countField;
            }
            set {
                this.ticket_close_countField = value;
            }
        }
        
        /// <remarks/>
        public int execute_day {
            get {
                return this.execute_dayField;
            }
            set {
                this.execute_dayField = value;
            }
        }
        
        /// <remarks/>
        public string strDate_info {
            get {
                return this.strDate_infoField;
            }
            set {
                this.strDate_infoField = value;
            }
        }
        
        /// <remarks/>
        public string execute_info {
            get {
                return this.execute_infoField;
            }
            set {
                this.execute_infoField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public int prj_id {
            get {
                return this.prj_idField;
            }
            set {
                this.prj_idField = value;
            }
        }
        
        /// <remarks/>
        public int cat_id {
            get {
                return this.cat_idField;
            }
            set {
                this.cat_idField = value;
            }
        }
        
        /// <remarks/>
        public string cat_title {
            get {
                return this.cat_titleField;
            }
            set {
                this.cat_titleField = value;
            }
        }
        
        /// <remarks/>
        public string director_san {
            get {
                return this.director_sanField;
            }
            set {
                this.director_sanField = value;
            }
        }
        
        /// <remarks/>
        public string director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
            }
        }
        
        /// <remarks/>
        public string director_img {
            get {
                return this.director_imgField;
            }
            set {
                this.director_imgField = value;
            }
        }
        
        /// <remarks/>
        public int work_days {
            get {
                return this.work_daysField;
            }
            set {
                this.work_daysField = value;
            }
        }
        
        /// <remarks/>
        public int vacation_days {
            get {
                return this.vacation_daysField;
            }
            set {
                this.vacation_daysField = value;
            }
        }
        
        /// <remarks/>
        public int est_working_hour {
            get {
                return this.est_working_hourField;
            }
            set {
                this.est_working_hourField = value;
            }
        }
        
        /// <remarks/>
        public bool approval_result {
            get {
                return this.approval_resultField;
            }
            set {
                this.approval_resultField = value;
            }
        }
        
        /// <remarks/>
        public string approval_details {
            get {
                return this.approval_detailsField;
            }
            set {
                this.approval_detailsField = value;
            }
        }
        
        /// <remarks/>
        public string finish_userSan {
            get {
                return this.finish_userSanField;
            }
            set {
                this.finish_userSanField = value;
            }
        }
        
        /// <remarks/>
        public int proggress_percent {
            get {
                return this.proggress_percentField;
            }
            set {
                this.proggress_percentField = value;
            }
        }
        
        /// <remarks/>
        public string strCurrentProggressPecrcent {
            get {
                return this.strCurrentProggressPecrcentField;
            }
            set {
                this.strCurrentProggressPecrcentField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string creted_san {
            get {
                return this.creted_sanField;
            }
            set {
                this.creted_sanField = value;
            }
        }
        
        /// <remarks/>
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> est_start {
            get {
                return this.est_startField;
            }
            set {
                this.est_startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> est_end {
            get {
                return this.est_endField;
            }
            set {
                this.est_endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> finish_date {
            get {
                return this.finish_dateField;
            }
            set {
                this.finish_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastTicket_finishDate {
            get {
                return this.lastTicket_finishDateField;
            }
            set {
                this.lastTicket_finishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastMajor_updateDate {
            get {
                return this.lastMajor_updateDateField;
            }
            set {
                this.lastMajor_updateDateField = value;
            }
        }
        
        /// <remarks/>
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> merging_date {
            get {
                return this.merging_dateField;
            }
            set {
                this.merging_dateField = value;
            }
        }
        
        /// <remarks/>
        public int merged_to {
            get {
                return this.merged_toField;
            }
            set {
                this.merged_toField = value;
            }
        }
        
        /// <remarks/>
        public string merging_info {
            get {
                return this.merging_infoField;
            }
            set {
                this.merging_infoField = value;
            }
        }
        
        /// <remarks/>
        public string merged_project_search_tag {
            get {
                return this.merged_project_search_tagField;
            }
            set {
                this.merged_project_search_tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class fava_project_summery {
        
        private project_info[] projectList_infoField;
        
        private project_ticket[] ticketsField;
        
        private project_ticket[] ticket_listField;
        
        private involved_user[] usersField;
        
        private project_info[] mergedPrj_infoField;
        
        private string error_messaageField;
        
        private string projectList_unitField;
        
        private string result_headerTitleField;
        
        /// <remarks/>
        public project_info[] projectList_info {
            get {
                return this.projectList_infoField;
            }
            set {
                this.projectList_infoField = value;
            }
        }
        
        /// <remarks/>
        public project_ticket[] tickets {
            get {
                return this.ticketsField;
            }
            set {
                this.ticketsField = value;
            }
        }
        
        /// <remarks/>
        public project_ticket[] ticket_list {
            get {
                return this.ticket_listField;
            }
            set {
                this.ticket_listField = value;
            }
        }
        
        /// <remarks/>
        public involved_user[] users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        public project_info[] mergedPrj_info {
            get {
                return this.mergedPrj_infoField;
            }
            set {
                this.mergedPrj_infoField = value;
            }
        }
        
        /// <remarks/>
        public string error_messaage {
            get {
                return this.error_messaageField;
            }
            set {
                this.error_messaageField = value;
            }
        }
        
        /// <remarks/>
        public string projectList_unit {
            get {
                return this.projectList_unitField;
            }
            set {
                this.projectList_unitField = value;
            }
        }
        
        /// <remarks/>
        public string result_headerTitle {
            get {
                return this.result_headerTitleField;
            }
            set {
                this.result_headerTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class reportResult {
        
        private string group_with_maxTicket_gidField;
        
        private string group_with_maxTicket_gNameField;
        
        private int group_with_maxTicket_countField;
        
        private double group_with_maxTicket_averageField;
        
        private string group_with_topAverage_gidField;
        
        private string group_with_topAverage_gNameField;
        
        private int group_with_topAverage_countField;
        
        private double group_with_topAverage_averageField;
        
        private int totall_ticket_countField;
        
        private System.DateTime day_with_maxTicket_dateField;
        
        private string day_with_maxTicket_farsiDateField;
        
        private int day_with_maxTicket_countField;
        
        private int totall_teobjField;
        
        /// <remarks/>
        public string group_with_maxTicket_gid {
            get {
                return this.group_with_maxTicket_gidField;
            }
            set {
                this.group_with_maxTicket_gidField = value;
            }
        }
        
        /// <remarks/>
        public string group_with_maxTicket_gName {
            get {
                return this.group_with_maxTicket_gNameField;
            }
            set {
                this.group_with_maxTicket_gNameField = value;
            }
        }
        
        /// <remarks/>
        public int group_with_maxTicket_count {
            get {
                return this.group_with_maxTicket_countField;
            }
            set {
                this.group_with_maxTicket_countField = value;
            }
        }
        
        /// <remarks/>
        public double group_with_maxTicket_average {
            get {
                return this.group_with_maxTicket_averageField;
            }
            set {
                this.group_with_maxTicket_averageField = value;
            }
        }
        
        /// <remarks/>
        public string group_with_topAverage_gid {
            get {
                return this.group_with_topAverage_gidField;
            }
            set {
                this.group_with_topAverage_gidField = value;
            }
        }
        
        /// <remarks/>
        public string group_with_topAverage_gName {
            get {
                return this.group_with_topAverage_gNameField;
            }
            set {
                this.group_with_topAverage_gNameField = value;
            }
        }
        
        /// <remarks/>
        public int group_with_topAverage_count {
            get {
                return this.group_with_topAverage_countField;
            }
            set {
                this.group_with_topAverage_countField = value;
            }
        }
        
        /// <remarks/>
        public double group_with_topAverage_average {
            get {
                return this.group_with_topAverage_averageField;
            }
            set {
                this.group_with_topAverage_averageField = value;
            }
        }
        
        /// <remarks/>
        public int totall_ticket_count {
            get {
                return this.totall_ticket_countField;
            }
            set {
                this.totall_ticket_countField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime day_with_maxTicket_date {
            get {
                return this.day_with_maxTicket_dateField;
            }
            set {
                this.day_with_maxTicket_dateField = value;
            }
        }
        
        /// <remarks/>
        public string day_with_maxTicket_farsiDate {
            get {
                return this.day_with_maxTicket_farsiDateField;
            }
            set {
                this.day_with_maxTicket_farsiDateField = value;
            }
        }
        
        /// <remarks/>
        public int day_with_maxTicket_count {
            get {
                return this.day_with_maxTicket_countField;
            }
            set {
                this.day_with_maxTicket_countField = value;
            }
        }
        
        /// <remarks/>
        public int totall_teobj {
            get {
                return this.totall_teobjField;
            }
            set {
                this.totall_teobjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAuthenticateRet {
        
        private string messageField;
        
        private string typeField;
        
        private object tokenField;
        
        private string user_sanField;
        
        private string user_cnField;
        
        private string user_imageField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public object token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string user_san {
            get {
                return this.user_sanField;
            }
            set {
                this.user_sanField = value;
            }
        }
        
        /// <remarks/>
        public string user_cn {
            get {
                return this.user_cnField;
            }
            set {
                this.user_cnField = value;
            }
        }
        
        /// <remarks/>
        public string user_image {
            get {
                return this.user_imageField;
            }
            set {
                this.user_imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConversationInfo {
        
        private int ticketIdField;
        
        private System.DateTime modifyDateField;
        
        private string senderField;
        
        private string senderCNField;
        
        private string senderImgField;
        
        private string reciverSanField;
        
        private int newMessagesCountField;
        
        private bool senderIsAGroupField;
        
        private bool senderIsAPoolField;
        
        /// <remarks/>
        public int TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
            }
        }
        
        /// <remarks/>
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public string SenderCN {
            get {
                return this.senderCNField;
            }
            set {
                this.senderCNField = value;
            }
        }
        
        /// <remarks/>
        public string SenderImg {
            get {
                return this.senderImgField;
            }
            set {
                this.senderImgField = value;
            }
        }
        
        /// <remarks/>
        public string ReciverSan {
            get {
                return this.reciverSanField;
            }
            set {
                this.reciverSanField = value;
            }
        }
        
        /// <remarks/>
        public int NewMessagesCount {
            get {
                return this.newMessagesCountField;
            }
            set {
                this.newMessagesCountField = value;
            }
        }
        
        /// <remarks/>
        public bool SenderIsAGroup {
            get {
                return this.senderIsAGroupField;
            }
            set {
                this.senderIsAGroupField = value;
            }
        }
        
        /// <remarks/>
        public bool SenderIsAPool {
            get {
                return this.senderIsAPoolField;
            }
            set {
                this.senderIsAPoolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewConversations {
        
        private string msgField;
        
        private string typeField;
        
        private ConversationInfo[] lstConversationsField;
        
        private UserAuthenticateRet userAuthenticateRetField;
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public ConversationInfo[] LstConversations {
            get {
                return this.lstConversationsField;
            }
            set {
                this.lstConversationsField = value;
            }
        }
        
        /// <remarks/>
        public UserAuthenticateRet UserAuthenticateRet {
            get {
                return this.userAuthenticateRetField;
            }
            set {
                this.userAuthenticateRetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ticketPool {
        
        private string msgField;
        
        private string typeField;
        
        private int[] lstTicketPool_doneField;
        
        private int[] lstTicketPool_errorField;
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int[] lstTicketPool_done {
            get {
                return this.lstTicketPool_doneField;
            }
            set {
                this.lstTicketPool_doneField = value;
            }
        }
        
        /// <remarks/>
        public int[] lstTicketPool_error {
            get {
                return this.lstTicketPool_errorField;
            }
            set {
                this.lstTicketPool_errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RankingUserInfo {
        
        private string user_sanField;
        
        private int ticketCount_closedInPeriodField;
        
        private int ticketCount_sendedInPeriodField;
        
        private int referenceCount_closedInPeriodField;
        
        private int referenceCount_ReferedInPeriodField;
        
        private double average_ticketsScoreField;
        
        private double average_ReferencesScoreField;
        
        private int notFinished_references_InPeriodField;
        
        private double negativeTicketCount_considerCoefficient_InPeriodField;
        
        private double ticketDeadline_delay_inSecondField;
        
        private double project_performance_coefficientField;
        
        private double avg_newTickets_SeenTime_inSecondField;
        
        private double sum_newMessages_SeenTime_inSecondField;
        
        private double avg_newMessages_SeenTime_inSecondField;
        
        /// <remarks/>
        public string user_san {
            get {
                return this.user_sanField;
            }
            set {
                this.user_sanField = value;
            }
        }
        
        /// <remarks/>
        public int ticketCount_closedInPeriod {
            get {
                return this.ticketCount_closedInPeriodField;
            }
            set {
                this.ticketCount_closedInPeriodField = value;
            }
        }
        
        /// <remarks/>
        public int ticketCount_sendedInPeriod {
            get {
                return this.ticketCount_sendedInPeriodField;
            }
            set {
                this.ticketCount_sendedInPeriodField = value;
            }
        }
        
        /// <remarks/>
        public int referenceCount_closedInPeriod {
            get {
                return this.referenceCount_closedInPeriodField;
            }
            set {
                this.referenceCount_closedInPeriodField = value;
            }
        }
        
        /// <remarks/>
        public int referenceCount_ReferedInPeriod {
            get {
                return this.referenceCount_ReferedInPeriodField;
            }
            set {
                this.referenceCount_ReferedInPeriodField = value;
            }
        }
        
        /// <remarks/>
        public double average_ticketsScore {
            get {
                return this.average_ticketsScoreField;
            }
            set {
                this.average_ticketsScoreField = value;
            }
        }
        
        /// <remarks/>
        public double average_ReferencesScore {
            get {
                return this.average_ReferencesScoreField;
            }
            set {
                this.average_ReferencesScoreField = value;
            }
        }
        
        /// <remarks/>
        public int notFinished_references_InPeriod {
            get {
                return this.notFinished_references_InPeriodField;
            }
            set {
                this.notFinished_references_InPeriodField = value;
            }
        }
        
        /// <remarks/>
        public double negativeTicketCount_considerCoefficient_InPeriod {
            get {
                return this.negativeTicketCount_considerCoefficient_InPeriodField;
            }
            set {
                this.negativeTicketCount_considerCoefficient_InPeriodField = value;
            }
        }
        
        /// <remarks/>
        public double ticketDeadline_delay_inSecond {
            get {
                return this.ticketDeadline_delay_inSecondField;
            }
            set {
                this.ticketDeadline_delay_inSecondField = value;
            }
        }
        
        /// <remarks/>
        public double project_performance_coefficient {
            get {
                return this.project_performance_coefficientField;
            }
            set {
                this.project_performance_coefficientField = value;
            }
        }
        
        /// <remarks/>
        public double avg_newTickets_SeenTime_inSecond {
            get {
                return this.avg_newTickets_SeenTime_inSecondField;
            }
            set {
                this.avg_newTickets_SeenTime_inSecondField = value;
            }
        }
        
        /// <remarks/>
        public double sum_newMessages_SeenTime_inSecond {
            get {
                return this.sum_newMessages_SeenTime_inSecondField;
            }
            set {
                this.sum_newMessages_SeenTime_inSecondField = value;
            }
        }
        
        /// <remarks/>
        public double avg_newMessages_SeenTime_inSecond {
            get {
                return this.avg_newMessages_SeenTime_inSecondField;
            }
            set {
                this.avg_newMessages_SeenTime_inSecondField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RankingTicketResult_forSan {
        
        private RankingUserInfo[] rankingUserInfo_listField;
        
        private string error_messaageField;
        
        /// <remarks/>
        public RankingUserInfo[] RankingUserInfo_list {
            get {
                return this.rankingUserInfo_listField;
            }
            set {
                this.rankingUserInfo_listField = value;
            }
        }
        
        /// <remarks/>
        public string error_messaage {
            get {
                return this.error_messaageField;
            }
            set {
                this.error_messaageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticateRetVal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticateRetVal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void logOutCompletedEventHandler(object sender, logOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTicketRankingResultCompletedEventHandler(object sender, GetTicketRankingResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTicketRankingResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTicketRankingResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RankingTicketResult_forSan Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RankingTicketResult_forSan)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AutoPickupTicketCompletedEventHandler(object sender, AutoPickupTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutoPickupTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutoPickupTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ticketPool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ticketPool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FetchNewConversations_CompletedEventHandler(object sender, FetchNewConversations_CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchNewConversations_CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchNewConversations_CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NewConversations Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NewConversations)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FetchNewConversationsCompletedEventHandler(object sender, FetchNewConversationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchNewConversationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchNewConversationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NewConversations Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NewConversations)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UserAuthenticateCompletedEventHandler(object sender, UserAuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAuthenticateRet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAuthenticateRet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Report_ticketSummeryCompletedEventHandler(object sender, Report_ticketSummeryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Report_ticketSummeryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Report_ticketSummeryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reportResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reportResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAllProjectsCompletedEventHandler(object sender, GetAllProjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fava_project_summery Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fava_project_summery)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetProjectCompletedEventHandler(object sender, GetProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public fava_project_summery Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((fava_project_summery)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ticketRandomChartCompletedEventHandler(object sender, ticketRandomChartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ticketRandomChartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ticketRandomChartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void findAdUsersCompletedEventHandler(object sender, findAdUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAdUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAdUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public adUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((adUser[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591